acl: explicitly initialize input
After the removal of the weak function mechansim in commit
e53ce4e41379 ("acl: remove use of weak functions") the AARCH64 build
will generate warnings about input being used uninitialized:

   ../lib/librte_acl/acl_run_neon.h: In function ‘search_neon_4’:
   ../lib/librte_acl/acl_run_neon.h:230:12: error: ‘input’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
     int32x4_t input;
               ^
   ../lib/librte_acl/acl_run_neon.h: In function ‘search_neon_8’:
   ../lib/librte_acl/acl_run_neon.h:168:20: error: ‘input1’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
     int32x4_t input0, input1;
                       ^
   ../lib/librte_acl/acl_run_neon.h:168:12: error: ‘input0’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
     int32x4_t input0, input1;
               ^
   cc1: all warnings being treated as errors

The specific intrinsic used to initialize the vector has no analog which
would allow initializing all lanes.  This results in the compiler incorrectly
treating the variables as uninitialized.

To address this, make the first 'pull' of lanes use an explicitly 0 value.

Signed-off-by: Aaron Conole <aconole@redhat.com>